
#' Simulated health enrolment data.
#'
#' The data set is generated by scaling population counts for 20 regions
#' in New Zealand by coverage rates that vary by age.
#'
#' @format  An array with dimensions \code{"age"}, \code{"sex"}, \code{"region"},
#' and \code{"year"}.
#'
#' @seealso The other simulated administrative datasets are
#' \code{\link{sim.admin.nat}}, \code{\link{sim.admin.school}},
#' and \code{\link{sim.admin.survey}}.  The underlying "simulation-true"
#' population counts are \code{\link{sim.popn.true}}.
"sim.admin.health"
