
#' Simulated counts of unemployed by age, sex, and region.
#'
#' One hundred simulated sets of counts of unemployed by age, sex, and region.
#' The rates were generated by making Poisson draws, with means equal to
#' \code{\link{sim.unemployment.rate}} multipled by \code{\link{sim.labor.force}}.
#'
#' @format An array with dimensions "age", "sex", "region", and "iteration".
#'
#' @seealso \code{link{sim.unemployment.rate}}, \code{\link{sim.labor.force}}
#'
#' @source Modifed from "Employment status of the civilian noninstitutional population
#' by age, sex, and race, retrieved from http://www.bls.gov/cps/cpsaat03.htm on 25 October 2015
"sim.unemployed"
